### ISSUE TITLE
Source code tarball URL needs updating

### ISSUE THREAD

**Issue by faithanalog** [mobile-shell/mobile-shell.github.io#75]
Under "building from source":

![image](https://github.com/mobile-shell/mobile-shell.github.io/assets/1389549/53be57d7-b028-4e75-8b1e-fbd1e6012fa5)

The linked `mosh-1.4.0.tar.gz` points to `https://mosh.org/mosh-1.4.0.tar.gz`, but I think it should point to `https://github.com/mobile-shell/mosh/releases/download/mosh-1.4.0/mosh-1.4.0.tar.gz`

**Comment by keithw** [comment]
Thanks for catching this!
